### ISSUE TITLE
Client crash on Forge Server 1.15.2

### ISSUE THREAD

**Issue by Jergeric** [yuitakaa/InvTweaksReborn#11]
Aloha, the client crashes when I try to sort an inventory (char&chest), not always but mostly.

If a log is still needed, I can provide it

[crash-2020-07-21_19.41.31-client.txt](https://github.com/reo-ar/InvTweaksRenewed/files/4955295/crash-2020-07-21_19.41.31-client.txt)

**Comment by reo-ar** [comment]
Fixed in commit fa21c97
