### ISSUE TITLE
[1.16.1] Error executing task on Server

### ISSUE THREAD

**Issue by Gbergz** [yuitakaa/InvTweaksReborn#12]
Title^

Getting this in console sometimes while players are online playing, is it something to be worried about?
Message: https://hastebin.com/isomirudol.rb

**MC:** 1.16.1
**Forge:** 32.0.71
**Mod Version:** 1.16.1-1.0.5

**-** Gbergz

**Comment by reo-ar** [comment]
This is nothing to worry much about, but it seems like it's an inventory it's not supposed to handle, I'll take a look into this.
A modlist would help very much

**Comment by Gbergz** [comment]
Here's the modlist
https://github.com/The-Nexus-Project/Limitless-3/blob/master/modlist

**Comment by reo-ar** [comment]
It might take a while to sort through which container causes this, but I will try to do it

**Comment by reo-ar** [comment]
Most likely this was due to the fact that Dank Storage units aren't compatible with sorting or some other inventory being incompatible, but I added a filter for Dank Storage for now. Closing re-open again if problem persists, although it is quite harmless.
