### ISSUE TITLE
java.lang.NullPointerException: keyPressed event handler

### ISSUE THREAD

**Issue by james090500** [yuitakaa/InvTweaksReborn#15]
In a crafting bench I was dragging some sand accross, then my game crashed with the attached error

https://paste.gg/p/anonymous/37b66433a903491c8b9eed774e615d51

**Comment by diamondwelsh** [comment]
Similar issue when middle-clicking to sort a chest

https://pastebin.com/FgTq4F8X

**Comment by james090500** [comment]
Closing this as it is just sitting open on my feed and it seems it's not being addressed
