### ISSUE TITLE
Implementing the hotkeys for moving items to/from containers

### ISSUE THREAD

**Issue by DoomSquirter** [yuitakaa/InvTweaksReborn#18]
Are you going to be implementing the other invtweaks useful ability to move items to/from containers with hotkeys?  Honestly, I use that functionality way more than sorting chests generally.

like move all of this type, or move all from this container.  these two things really are all I actually care about.

**Comment by reo-ar** [comment]
This has been implemented in another mod https://www.curseforge.com/minecraft/mc-mods/inventory-essentials
