### ISSUE TITLE
[1.16.x] Forge Tags causing crash

### ISSUE THREAD

**Issue by CosmicGoldFish** [yuitakaa/InvTweaksReborn#2]
[crash-2020-06-27_18.29.51-client.txt](https://github.com/yuitakaa/InvTweaksRenewed/files/4841432/crash-2020-06-27_18.29.51-client.txt)

crash when sorting an inventory while connected to a Spigot 1.16.1 server, works fine in singleplayer

[edit] Works when sorting a chest, only crashes when sorting my own player inventory

**Comment by reo-ar** [comment]
Item tags on Forge is pretty buggy right now, I'll probably upload a fix without custom tags first if it's not fixed soon.

**Comment by reo-ar** [comment]
Fixed on Forge/Vanilla servers now after the latest Forge updates. Paper handles mouseclicked event differently and may produce unwanted results. Closing.
