### ISSUE TITLE
Sort/Search buttons in awkward locations in some UI Windows

### ISSUE THREAD

**Issue by Danekjovax** [yuitakaa/InvTweaksReborn#30]
I am playing Explorico 1.4, and seeing issues with InvTweaksRenewed possibly putting its search/sort buttons in awkward locations in a few UI windows of some crafting tables from other mods.  Mod info and screenshots below:

Engineer's Crafting Table (Immersive Engineering):
![image](https://user-images.githubusercontent.com/10191173/103144047-b0f6ed00-46f0-11eb-9b56-667420c90545.png)

Project Table (BluePower):
![image](https://user-images.githubusercontent.com/10191173/103144066-1ba82880-46f1-11eb-834d-9517dad886c7.png)

I'm not sure what's causing this to happen, but if there was some config to allow some ability for modpack authors to disable these buttons for specific objects that would be great.

Mod version info:
bluepower-1.16.4-0.5.223-alpha-universal
forge-1.16.4-35.1.13-universal
invtweaks-1.16.4-1.0.1
ImmersiveEngineering-1.16.4-4.1.2-129

Thanks!

**Comment by Freebi85** [comment]
In addition to this one, In Artisan Tables they're also a bit messed up.
![image](https://user-images.githubusercontent.com/42634622/105520997-a4f45000-5cdb-11eb-97e1-ec78d3339d28.png)

**Comment by Danekjovax** [comment]
It seems this is a misdirected issue, so I'm closing it.  Sorry for the trouble. ;2)
