### ISSUE TITLE
NPE while using InvTweaks on BungeeCord network

### ISSUE THREAD

**Issue by Joo200** [yuitakaa/InvTweaksReborn#6]
Not entirely sure why there is a NPE.

the point of the NPE should be here: https://github.com/reo-ar/InvTweaksRenewed/blob/1.15.x/src/main/java/invtweaks/util/Sorting.java#L307

The paste points to another line but that version seems to be a few days old.
https://paste.ee/p/EOMpS

**Comment by reo-ar** [comment]
mouseClicked event handler is at fault here, I'll try workarounds in a bit.

**Comment by reo-ar** [comment]
Closing issue as it's redundant
