### ISSUE TITLE
Crash on sort 1.16.1

### ISSUE THREAD

**Issue by whatthedrunk** [yuitakaa/InvTweaksReborn#8]
Getting this crash on ATM6 https://pastebin.com/jGw0XD73

**Comment by whatthedrunk** [comment]
Here is another https://pastebin.com/Xgvt4sST

**Comment by tugboat-maguire** [comment]
same here: https://pastebin.com/89AHwbPM

**Comment by reo-ar** [comment]
Please do remove Optifine if it's a screen related bug, also for the third issue Paper servers aren't supported because they handle some things different.

Pushing an update with more null checks to see if it helps

**Comment by reo-ar** [comment]
Closing this as it's redundant and the issue is in the megathread
